import { Prisma } from "@prisma/client";
import { db } from "../db";
import type { DeliveryStore } from "./service";
export class PrismaDeliveryStore implements DeliveryStore {
  async claimBatch(organizationId:string,workerId:string,now:Date,leaseExpiredAt:Date,limit:number){return db.$queryRaw<Array<{id:string;organizationId:string;recipientUserId:string|null;recipientAddress:string|null;channel:"IN_APP"|"EMAIL";templateKey:string;payload:unknown;attempts:number}>>(Prisma.sql`
    WITH candidates AS (SELECT n."id" FROM "NotificationOutbox" n WHERE n."organizationId"=${organizationId}::uuid AND ((n."status" IN ('PENDING','FAILED') AND n."availableAt"<=${now}) OR (n."status"='PROCESSING' AND n."claimedAt"<${leaseExpiredAt})) ORDER BY n."availableAt",n."createdAt" FOR UPDATE SKIP LOCKED LIMIT ${limit}),
    claimed AS (UPDATE "NotificationOutbox" n SET "status"='PROCESSING',"claimedAt"=${now},"claimedBy"=${workerId},"lastAttemptAt"=${now} FROM candidates c WHERE n."id"=c."id" RETURNING n.*)
    SELECT c."id",c."organizationId",c."recipientUserId",u."email" AS "recipientAddress",c."channel"::text AS "channel",c."templateKey",c."payload",c."attempts" FROM claimed c LEFT JOIN "User" u ON u."organizationId"=c."organizationId" AND u."id"=c."recipientUserId"`);}
  async markSent(id:string,workerId:string,sentAt:Date){const r=await db.notificationOutbox.updateMany({where:{id,status:"PROCESSING",claimedBy:workerId},data:{status:"SENT",sentAt,claimedAt:null,claimedBy:null,attempts:{increment:1},lastError:null}});return r.count===1;}
  async markFailed(id:string,workerId:string,input:{failedAt:Date;availableAt:Date;error:string;deadLetter:boolean}){const r=await db.notificationOutbox.updateMany({where:{id,status:"PROCESSING",claimedBy:workerId},data:{status:input.deadLetter?"DEAD_LETTER":"FAILED",attempts:{increment:1},lastAttemptAt:input.failedAt,availableAt:input.availableAt,lastError:input.error,deadLetteredAt:input.deadLetter?input.failedAt:null,claimedAt:null,claimedBy:null}});return r.count===1;}
  async listInbox(organizationId:string,userId:string){return db.notificationOutbox.findMany({where:{organizationId,recipientUserId:userId,channel:"IN_APP",status:"SENT"},select:{id:true,templateKey:true,payload:true,sentAt:true,readAt:true},orderBy:{sentAt:"desc"},take:200});}
  async markRead(organizationId:string,userId:string,id:string,readAt:Date){const r=await db.notificationOutbox.updateMany({where:{organizationId,recipientUserId:userId,id,channel:"IN_APP",status:"SENT",readAt:null},data:{readAt}});if(r.count===1)return true;return Boolean(await db.notificationOutbox.findFirst({where:{organizationId,recipientUserId:userId,id,channel:"IN_APP",status:"SENT",readAt:{not:null}},select:{id:true}}));}
  async listDeliveryFailures(organizationId:string){return db.notificationOutbox.findMany({where:{organizationId,status:{in:["FAILED","DEAD_LETTER"]}},select:{id:true,status:true,attempts:true,lastError:true,availableAt:true},orderBy:{lastAttemptAt:"desc"},take:500});}
  async requeue(organizationId:string,id:string,actorUserId:string,now:Date){return db.$transaction(async(transaction)=>{const r=await transaction.notificationOutbox.updateMany({where:{organizationId,id,status:"DEAD_LETTER"},data:{status:"PENDING",attempts:0,availableAt:now,lastError:null,deadLetteredAt:null}});if(r.count!==1)return false;await transaction.auditEvent.create({data:{organizationId,actorUserId,action:"NOTIFICATION_REQUEUED",entityType:"NotificationOutbox",entityId:id,occurredAt:now}});return true;});}
}
export const inAppTransport={async deliver(){return;}};
