import { describe,expect,it } from "vitest";
import type { AuthorizationContext } from "../security/authorization";
import { NotificationDeliveryService,NotificationInboxService,type ClaimedNotification,type DeliveryStore } from "./service";
const admin:AuthorizationContext={userId:"admin",organizationId:"org-1",userState:"ACTIVE",grants:[{permission:"notification.manage",scopeType:"ORGANIZATION",scopeId:null}]};
function fixture(fail=false,attempts=0){let state="PROCESSING",read=false;const item:ClaimedNotification={id:"n1",organizationId:"org-1",recipientUserId:"admin",recipientAddress:"a@example.test",channel:"IN_APP",templateKey:"DUE",payload:{},attempts};const store:DeliveryStore={async claimBatch(org){return org==="org-1"?[item]:[]},async markSent(){state="SENT";return true},async markFailed(_id,_worker,input){state=input.deadLetter?"DEAD_LETTER":"FAILED";return true},async listInbox(org,user){return org==="org-1"&&user==="admin"?[{id:"n1",templateKey:"DUE",payload:{},sentAt:new Date(),readAt:read?new Date():null}]:[]},async markRead(org,user,id){if(org!=="org-1"||user!=="admin"||id!=="n1")return false;read=true;return true},async listDeliveryFailures(){return[{id:"n1",status:state,attempts,lastError:null,availableAt:new Date()}]},async requeue(){if(state!=="DEAD_LETTER")return false;state="PENDING";return true}};const transport={async deliver(){if(fail)throw new Error("provider unavailable")}};return{store,transport,getState:()=>state};}
describe("notification delivery",()=>{
 it("claims only the requested tenant and marks successful delivery",async()=>{const f=fixture();const service=new NotificationDeliveryService(f.store,{IN_APP:f.transport,EMAIL:f.transport});await expect(service.process("org-1","worker-1")).resolves.toMatchObject({claimed:1,sent:1});await expect(service.process("org-2","worker-1")).resolves.toMatchObject({claimed:0});expect(f.getState()).toBe("SENT");});
 it("retries transient failures and dead-letters the fifth attempt",async()=>{const retry=fixture(true,1);await new NotificationDeliveryService(retry.store,{IN_APP:retry.transport,EMAIL:retry.transport}).process("org-1","worker-1");expect(retry.getState()).toBe("FAILED");const final=fixture(true,4);await expect(new NotificationDeliveryService(final.store,{IN_APP:final.transport,EMAIL:final.transport}).process("org-1","worker-1")).resolves.toMatchObject({deadLettered:1});expect(final.getState()).toBe("DEAD_LETTER");});
 it("enforces inbox ownership and permits idempotent read",async()=>{const f=fixture();const inbox=new NotificationInboxService(f.store);await expect(inbox.list(admin,"org-1")).resolves.toHaveLength(1);await expect(inbox.markRead(admin,{organizationId:"org-1",notificationId:"n1"})).resolves.toEqual({read:true});await expect(inbox.list({...admin,userId:"other"},"org-2")).rejects.toThrow("Access denied");});
 it("restricts failure monitoring and dead-letter requeue to administrators",async()=>{const f=fixture(true,4);await new NotificationDeliveryService(f.store,{IN_APP:f.transport,EMAIL:f.transport}).process("org-1","worker-1");const inbox=new NotificationInboxService(f.store);await expect(inbox.failures(admin,"org-1")).resolves.toHaveLength(1);await expect(inbox.requeue(admin,{organizationId:"org-1",notificationId:"n1"})).resolves.toEqual({requeued:true});});
});
