import { describe,expect,it } from "vitest";
import type { AuthorizationContext } from "../security/authorization";
import { DocumentReviewService,type ReviewStore } from "./service";
const manager:AuthorizationContext={userId:"manager",organizationId:"org-1",userState:"ACTIVE",grants:[{permission:"document.review.manage",scopeType:"ORGANIZATION",scopeId:null},{permission:"document.review.complete",scopeType:"ORGANIZATION",scopeId:null}]};
function fixture(){const escalations:number[]=[];let completed=false;const due={id:"r1",documentId:"d1",documentVersionId:"v1",dueAt:new Date("2026-07-01T00:00:00Z")};const store:ReviewStore={async listDue(){return[due]},async listOutstanding(_o,now){return[{...due,overdue:due.dueAt<now}]},async escalate(i){if(escalations.includes(i.level))return false;escalations.push(i.level);return true},async complete(){if(completed)return false;completed=true;return true}};return{store,escalations};}
describe("periodic document review",()=>{
 it("creates one idempotent escalation level for overdue reviews",async()=>{const f=fixture();const s=new DocumentReviewService(f.store,()=>new Date("2026-08-24T00:00:00Z"));await expect(s.monitor(manager,"org-1")).resolves.toEqual({evaluated:1,escalated:1});await expect(s.monitor(manager,"org-1")).resolves.toEqual({evaluated:1,escalated:0});expect(f.escalations).toEqual([3]);});
 it("reports overdue state server-side and blocks cross-tenant access",async()=>{const s=new DocumentReviewService(fixture().store,()=>new Date("2026-08-24T00:00:00Z"));await expect(s.listOutstanding(manager,"org-1")).resolves.toEqual([expect.objectContaining({overdue:true})]);await expect(s.listOutstanding(manager,"org-2")).rejects.toThrow("Access denied");});
 it("completes once with a controlled outcome and comments",async()=>{const s=new DocumentReviewService(fixture().store);await expect(s.complete(manager,{organizationId:"org-1",taskId:"r1",outcome:"NO_CHANGE",comments:"Reviewed; content remains current."})).resolves.toEqual({completed:true});await expect(s.complete(manager,{organizationId:"org-1",taskId:"r1",outcome:"NO_CHANGE",comments:"Again"})).rejects.toThrow("changed");});
 it("rejects missing rationale",async()=>{await expect(new DocumentReviewService(fixture().store).complete(manager,{organizationId:"org-1",taskId:"r1",outcome:"REVISION_REQUIRED",comments:" "})).rejects.toThrow("required");});
});
