import { describe, expect, it } from "vitest";
import { hashPassword } from "../security/crypto";
import type { AuthorizationContext } from "../security/authorization";
import { AcknowledgmentService, type AcknowledgmentStore } from "./service";

const distributor: AuthorizationContext = { userId: "admin-1", organizationId: "org-1", userState: "ACTIVE", grants: [{ permission: "document.distribute", scopeType: "ORGANIZATION", scopeId: null }] };
const recipient: AuthorizationContext = { userId: "user-1", organizationId: "org-1", userState: "ACTIVE", grants: [{ permission: "document.acknowledge", scopeType: "ORGANIZATION", scopeId: null }] };
function fixture(status = "EFFECTIVE") { const failures: Date[] = []; const completions: unknown[] = []; const store: AcknowledgmentStore = { async assign(i) { return { created: i.recipientUserIds.length }; }, async loadAssignment(org,id,user) { return org === "org-1" && id === "ack-1" && user === "user-1" ? { organizationId: org, userId: user, assignmentId: id, documentId: "doc-1", documentVersionId: "v-1", revisionLabel: "1.0", contentHash: "a".repeat(64), passwordHash: hashPassword("correct horse battery staple"), assignmentStatus: "ASSIGNED", documentStatus: status, recipientStatus: "ACTIVE" } : null; }, async recentFailures() { return 0; }, async recordFailure(_e,at) { failures.push(at); }, async complete(i) { completions.push(i); return { completionId: "done-1" }; } }; return { store, failures, completions }; }
describe("controlled distribution", () => {
  it("assigns a future-due exact version to unique recipients", async () => { const f=fixture(); const service=new AcknowledgmentService(f.store,()=>new Date("2026-08-24T21:00:00Z")); await expect(service.assign(distributor,{organizationId:"org-1",versionId:"v-1",recipientUserIds:["u1","u2"],dueAt:new Date("2026-09-01T00:00:00Z")})).resolves.toEqual({created:2}); });
  it("rejects duplicate recipients and cross-tenant distribution", async () => { const service=new AcknowledgmentService(fixture().store); await expect(service.assign(distributor,{organizationId:"org-1",versionId:"v",recipientUserIds:["u1","u1"],dueAt:new Date(Date.now()+100000)})).rejects.toThrow("unique"); await expect(service.assign(distributor,{organizationId:"org-2",versionId:"v",recipientUserIds:["u1"],dueAt:new Date(Date.now()+100000)})).rejects.toThrow("Access denied"); });
  it("reauthenticates and signs the assigned exact version", async () => { const f=fixture(); const service=new AcknowledgmentService(f.store,()=>new Date("2026-08-24T21:00:00Z")); await expect(service.complete(recipient,{organizationId:"org-1",assignmentId:"ack-1",password:"correct horse battery staple",confirmed:true})).resolves.toMatchObject({completionId:"done-1"}); expect(f.completions).toHaveLength(1); });
  it("records wrong passwords and rejects superseded versions", async () => { const f=fixture(); const service=new AcknowledgmentService(f.store); await expect(service.complete(recipient,{organizationId:"org-1",assignmentId:"ack-1",password:"wrong",confirmed:true})).rejects.toThrow("Reauthentication"); expect(f.failures).toHaveLength(1); await expect(new AcknowledgmentService(fixture("SUPERSEDED").store).complete(recipient,{organizationId:"org-1",assignmentId:"ack-1",password:"correct horse battery staple",confirmed:true})).rejects.toThrow("eligible"); });
});
