"use client";

import { useEffect, useState, type FormEvent } from "react";
type AdminData = { organization: { displayName: string; loginCode: string }; sites: Array<{ id: string; name: string }>; departments: Array<{ id: string; name: string; siteId: string | null }>; users: Array<{ id: string; email: string; firstName: string; lastName: string; status: string; roles: Array<{ roleId: string }> }>; roles: Array<{ id: string; name: string; permissions: Array<{ permission: { key: string } }> }>; permissions: Array<{ key: string }> };

export function AccessAdministration() {
  const [data, setData] = useState<AdminData | null>(null), [error, setError] = useState(""), [notice, setNotice] = useState("");
  async function load() { const response = await fetch("/api/admin"); const body = await response.json().catch(() => null); if (response.ok) setData(body.data); else setError(body?.error ?? "Administration could not be loaded."); }
  useEffect(() => { let active = true; fetch("/api/admin").then(async (response) => ({ response, body: await response.json().catch(() => null) })).then(({ response, body }) => { if (!active) return; if (response.ok) setData(body.data); else setError(body?.error ?? "Administration could not be loaded."); }); return () => { active = false; }; }, []);
  async function command(payload: Record<string, unknown>) { setError(""); setNotice(""); const response = await fetch("/api/admin/commands", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json().catch(() => null); if (!response.ok) return setError(body?.error ?? "Change could not be completed."); setNotice("The controlled administration change was completed and audited."); await load(); }
  function form(operation: string, fields: (form: FormData) => Record<string, unknown>) { return (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const formData = new FormData(event.currentTarget); command({ operation, ...fields(formData) }); event.currentTarget.reset(); }; }
  if (!data) return <section className="panel documents-panel"><p>{error || "Loading access administration…"}</p></section>;
  return <section className="panel documents-panel"><div className="panel-header"><div><h2>Organization and access administration</h2><p>{data.organization.displayName} · {data.organization.loginCode}</p></div></div>{error && <div className="detail-error" role="alert">{error}</div>}{notice && <div className="detail-notice">{notice}</div>}<div className="template-layout">
    <form className="template-form" onSubmit={form("CREATE_SITE", (f) => ({ name: String(f.get("name")) }))}><strong>Add site</strong><label>Name<input name="name" required /></label><button className="primary-button">Create site</button></form>
    <form className="template-form" onSubmit={form("CREATE_DEPARTMENT", (f) => ({ name: String(f.get("name")), siteId: String(f.get("siteId")) || null }))}><strong>Add department</strong><label>Name<input name="name" required /></label><label>Site<select name="siteId"><option value="">Organization-wide</option>{data.sites.map((site) => <option value={site.id} key={site.id}>{site.name}</option>)}</select></label><button className="primary-button">Create department</button></form>
    <form className="template-form" onSubmit={form("CREATE_USER", (f) => ({ email: String(f.get("email")), firstName: String(f.get("firstName")), lastName: String(f.get("lastName")), temporaryPassword: String(f.get("temporaryPassword")) }))}><strong>Add user</strong><label>First name<input name="firstName" required /></label><label>Last name<input name="lastName" required /></label><label>Email<input name="email" type="email" required /></label><label>Temporary password<input name="temporaryPassword" type="password" minLength={12} required autoComplete="new-password" /></label><button className="primary-button">Create user</button></form>
    <form className="template-form" onSubmit={form("CREATE_ROLE", (f) => ({ name: String(f.get("name")), permissionKeys: f.getAll("permissionKeys").map(String) }))}><strong>Add role</strong><label>Name<input name="name" required /></label><fieldset><legend>Permissions</legend>{data.permissions.map((permission) => <label key={permission.key}><input type="checkbox" name="permissionKeys" value={permission.key} /> {permission.key}</label>)}</fieldset><button className="primary-button">Create role</button></form>
    <form className="template-form" onSubmit={form("ASSIGN_ROLE", (f) => ({ userId: String(f.get("userId")), roleId: String(f.get("roleId")) }))}><strong>Assign role</strong><label>User<select name="userId" required>{data.users.map((user) => <option value={user.id} key={user.id}>{user.firstName} {user.lastName} · {user.email}</option>)}</select></label><label>Role<select name="roleId" required>{data.roles.map((role) => <option value={role.id} key={role.id}>{role.name}</option>)}</select></label><button className="primary-button">Assign role</button></form>
  </div></section>;
}
