"use client";
import { useEffect, useState, type FormEvent } from "react";
type Row = { id: string; originalName: string; mimeType: string; sizeBytes: string; sha256: string; status: string; createdAt: string };
export function ControlledFiles({ canCreate }: { canCreate: boolean }) {
  const [rows, setRows] = useState<Row[]>([]), [error, setError] = useState(""), [uploading, setUploading] = useState(false);
  async function load() { const response = await fetch("/api/files"); const body = await response.json().catch(() => null); if (response.ok) setRows(body.data); else setError(body?.error ?? "Files could not be loaded."); }
  useEffect(() => { let active = true; fetch("/api/files").then(async (response) => ({ response, body: await response.json().catch(() => null) })).then(({ response, body }) => { if (!active) return; if (response.ok) setRows(body.data); else setError(body?.error ?? "Files could not be loaded."); }); return () => { active = false; }; }, []);
  async function upload(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setUploading(true); setError(""); const response = await fetch("/api/files", { method: "POST", body: new FormData(event.currentTarget) }); const body = await response.json().catch(() => null); setUploading(false); if (!response.ok) return setError(body?.error ?? "Upload failed."); event.currentTarget.reset(); await load(); }
  return <section className="panel documents-panel"><div className="panel-header"><div><h2>Private controlled files</h2><p>Uploads remain unavailable until an external malware scanner reports clean</p></div><span className="count-pill">{rows.length}</span></div>{canCreate && <form className="file-upload" onSubmit={upload}><input name="file" type="file" accept=".pdf,.docx,.xlsx,.txt" required /><button className="primary-button" disabled={uploading}>{uploading ? "Uploading…" : "Upload file"}</button></form>}{error && <div className="detail-error" role="alert">{error}</div>}<div className="table-wrap"><table><thead><tr><th>File</th><th>Status</th><th>Size</th><th>Integrity</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>{row.status === "AVAILABLE" ? <a href={`/api/files/${row.id}`}>{row.originalName}</a> : row.originalName}<span>{row.mimeType}</span></td><td>{row.status.replaceAll("_", " ")}</td><td>{Math.ceil(Number(row.sizeBytes) / 1024)} KB</td><td><code>{row.sha256.slice(0, 12)}…</code></td></tr>)}</tbody></table></div></section>;
}
