"use client";

import { useEffect, useMemo, useState, type FormEvent } from "react";
import { Icon, type IconName } from "./icon";
import { filterDashboardDocuments, summarizeOperationalData } from "@/lib/documents/dashboard";

type ApiStatus = "DRAFT" | "IN_REVIEW" | "APPROVED" | "EFFECTIVE" | "SUPERSEDED" | "RETIRED";
type Status = "Draft" | "In review" | "Approved" | "Effective" | "Superseded" | "Retired" | "Review due";
type DocumentRow = { id:string; title:string; type:string; version:string; status:Status; owner:string; effective:string; due:string };
type DocumentTypeOption = { id:string; code:string; name:string };
type DocumentApiRow = { id:string; documentNumber:string; title:string; type:string; revisionLabel:string; status:ApiStatus; owner:string; effectiveAt:string|null; reviewDueAt:string|null };
type DocumentPage = { items:DocumentApiRow[]; nextCursor:string|null; types:DocumentTypeOption[] };
type ReviewRow = { id:string; documentNumber:string; title:string; revisionLabel:string; dueAt:string; overdue:boolean };
type NotificationRow = { id:string; templateKey:string; payload:unknown; sentAt:string|null; readAt:string|null };
type FailureRow = { id:string; status:string; attempts:number; lastError:string|null; availableAt:string };
type LiveData = { organizationId:string; capabilities:{ canReadDocuments:boolean; canCreateDocuments:boolean; canManageReviews:boolean; canManageNotifications:boolean }; notifications:NotificationRow[]; reviews:ReviewRow[]; failures:FailureRow[] };
type View = "Documents" | "Review queue" | "Administration";

const initialDocuments:DocumentRow[] = [
 {id:"SOP-001",title:"Specimen Collection and Handling",type:"Standard Operating Procedure",version:"4.2",status:"Effective",owner:"Quality Systems",effective:"Aug 12, 2026",due:"Aug 12, 2027"},
 {id:"POL-014",title:"Document and Record Control",type:"Quality Policy",version:"3.0",status:"In review",owner:"James Ramsey",effective:"—",due:"Aug 28, 2026"},
 {id:"WI-032",title:"Daily Temperature Monitoring",type:"Work Instruction",version:"2.1",status:"Review due",owner:"Laboratory Operations",effective:"Sep 3, 2025",due:"Sep 3, 2026"},
 {id:"FRM-022",title:"Corrective Action Investigation",type:"Controlled Form",version:"1.0",status:"Draft",owner:"Quality Systems",effective:"—",due:"—"},
];
const nav:{label:string;icon:IconName}[] = [{label:"Documents",icon:"file"},{label:"Review queue",icon:"review"},{label:"Administration",icon:"settings"}];
const statusLabel:Record<ApiStatus,Status> = {DRAFT:"Draft",IN_REVIEW:"In review",APPROVED:"Approved",EFFECTIVE:"Effective",SUPERSEDED:"Superseded",RETIRED:"Retired"};
const date = (value:string|null) => value ? new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric"}).format(new Date(value)) : "—";
function StatusBadge({status}:{status:Status}) { return <span className={`status status-${status.toLowerCase().replaceAll(" ","-")}`}><span/>{status}</span>; }
function payloadSummary(payload:unknown) { if(!payload||typeof payload!=="object")return "Quality system notification";const p=payload as Record<string,unknown>;return typeof p.documentId==="string"?`Document ${p.documentId.slice(0,8)} · escalation level ${String(p.level??1)}`:"Quality system notification"; }
function mapDocument(row:DocumentApiRow):DocumentRow { const mappedStatus=row.reviewDueAt&&new Date(row.reviewDueAt)<new Date()&&row.status==="EFFECTIVE"?"Review due":statusLabel[row.status];return{id:row.documentNumber,title:row.title,type:row.type,version:row.revisionLabel,status:mappedStatus,owner:row.owner,effective:date(row.effectiveAt),due:date(row.reviewDueAt)}; }

export function DocumentControlDashboard() {
 const [documents,setDocuments]=useState(initialDocuments),[documentTypes,setDocumentTypes]=useState<DocumentTypeOption[]>([]),[nextCursor,setNextCursor]=useState<string|null>(null),[cursor,setCursor]=useState<string|null>(null),[cursorHistory,setCursorHistory]=useState<Array<string|null>>([]),[documentsLoading,setDocumentsLoading]=useState(false),[documentsError,setDocumentsError]=useState("");
 const [query,setQuery]=useState(""),[filter,setFilter]=useState("ALL"),[dialog,setDialog]=useState(false),[submitting,setSubmitting]=useState(false),[mobileNav,setMobileNav]=useState(false),[notice,setNotice]=useState(""),[view,setView]=useState<View>("Documents"),[live,setLive]=useState<LiveData|null>(null),[inboxOpen,setInboxOpen]=useState(false),[loading,setLoading]=useState(true),[documentReload,setDocumentReload]=useState(0);
 const visible=useMemo(()=>live?documents:filterDashboardDocuments(documents,query,filter==="ALL"?"All documents":statusLabel[filter as ApiStatus]),[documents,query,filter,live]);
 const summary=summarizeOperationalData({notifications:live?.notifications??[],reviews:live?.reviews??[],failures:live?.failures??[]}),unread=summary.unread,overdue=summary.overdue;

 useEffect(()=>{let active=true;fetch("/api/workspace/dashboard",{credentials:"same-origin"}).then(async response=>response.ok?response.json():null).then(body=>{if(active&&body?.data)setLive(body.data)}).catch(()=>{}).finally(()=>{if(active)setLoading(false)});return()=>{active=false};},[]);
 useEffect(()=>{if(!live?.capabilities.canReadDocuments)return;const controller=new AbortController(),timer=setTimeout(()=>{setDocumentsLoading(true);setDocumentsError("");const params=new URLSearchParams({limit:"25"});if(query.trim())params.set("query",query.trim());if(filter!=="ALL")params.set("status",filter);if(cursor)params.set("cursor",cursor);fetch(`/api/documents?${params}`,{credentials:"same-origin",signal:controller.signal}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error||"Unable to load documents");return body.data as DocumentPage;}).then(page=>{setDocuments(page.items.map(mapDocument));setDocumentTypes(page.types);setNextCursor(page.nextCursor);}).catch(error=>{if(error instanceof Error&&error.name!=="AbortError")setDocumentsError("Controlled documents could not be loaded.");}).finally(()=>setDocumentsLoading(false));},250);return()=>{clearTimeout(timer);controller.abort();};},[live?.capabilities.canReadDocuments,query,filter,cursor,documentReload]);
 function resetDocumentQuery(nextQuery?:string,nextFilter?:string){if(nextQuery!==undefined)setQuery(nextQuery);if(nextFilter!==undefined)setFilter(nextFilter);setCursor(null);setCursorHistory([]);}
 async function createDraft(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!live?.capabilities.canCreateDocuments)return;setSubmitting(true);setNotice("");const form=new FormData(event.currentTarget);const response=await fetch("/api/documents/commands",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({operation:"CREATE_DRAFT",documentTypeId:String(form.get("type")),documentNumber:String(form.get("number")),title:String(form.get("title")),versionNumber:1,revisionLabel:"0.1",contentText:String(form.get("content")),changeSummary:String(form.get("summary"))})});const body=await response.json().catch(()=>null);setSubmitting(false);if(!response.ok){setNotice(body?.error||"The draft could not be created.");return;}setDialog(false);resetDocumentQuery("","ALL");setDocumentReload(value=>value+1);setNotice(`${String(form.get("number"))} was saved as controlled draft version 0.1.`);}
 async function markRead(item:NotificationRow){if(!live||item.readAt)return;const response=await fetch("/api/notifications",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({operation:"READ",organizationId:live.organizationId,notificationId:item.id})});if(response.ok)setLive({...live,notifications:live.notifications.map(row=>row.id===item.id?{...row,readAt:new Date().toISOString()}:row)});}
 async function requeue(item:FailureRow){if(!live)return;const response=await fetch("/api/notifications",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({operation:"REQUEUE",organizationId:live.organizationId,notificationId:item.id})});if(response.ok){setLive({...live,failures:live.failures.filter(row=>row.id!==item.id)});setNotice("Dead-letter notification was requeued and the action was audited.");}}
 return <div className="app-shell">
  <aside className={`sidebar ${mobileNav?"sidebar-open":""}`}><div className="brand"><div className="brand-mark"><Icon name="shield"/></div><div><strong>TRACE</strong><span>QUALITY SYSTEMS</span></div></div><button className="sidebar-close" aria-label="Close navigation" onClick={()=>setMobileNav(false)}><Icon name="close"/></button><div className="workspace"><span>WORKSPACE</span><button>Trace Scientific<Icon name="chevron"/></button></div><nav aria-label="Primary navigation">{nav.map(item=><button key={item.label} className={view===item.label?"active":""} onClick={()=>{setView(item.label as View);setMobileNav(false);}}><Icon name={item.icon}/><span>{item.label}</span>{item.label==="Review queue"&&overdue>0&&<b>{overdue}</b>}</button>)}</nav><div className="sidebar-foot"><div className="compliance"><Icon name="shield"/><div><strong>Audit controls active</strong><span>Evidence is append-only</span></div></div><div className="user-card"><div className="avatar">JR</div><div><strong>James Ramsey</strong><span>Quality Administrator</span></div><Icon name="more"/></div></div></aside>
  <div className="main-column"><header className="topbar"><button className="mobile-menu" aria-label="Open navigation" onClick={()=>setMobileNav(true)}><Icon name="menu"/></button><div className="global-search"><Icon name="search"/><input aria-label="Global search" placeholder="Search QMS records"/><kbd>⌘ K</kbd></div><button className="icon-button" aria-label={`${unread} unread notifications`} aria-expanded={inboxOpen} onClick={()=>setInboxOpen(!inboxOpen)}><Icon name="bell"/>{unread>0&&<span className="notification-count">{unread}</span>}</button><div className="top-avatar">JR</div></header>
  {inboxOpen&&<aside className="notification-drawer" aria-label="Notifications"><div className="drawer-head"><div><h2>Notifications</h2><p>{unread} unread</p></div><button aria-label="Close notifications" onClick={()=>setInboxOpen(false)}><Icon name="close"/></button></div>{live?.notifications.length?live.notifications.map(item=><button key={item.id} className={`notification-item ${item.readAt?"":"unread"}`} onClick={()=>markRead(item)}><span className="activity-dot amber"><Icon name="clock"/></span><span><strong>{item.templateKey.replaceAll("_"," ")}</strong><small>{payloadSummary(item.payload)}</small><time>{date(item.sentAt)}</time></span></button>):<div className="drawer-empty"><Icon name="bell"/><strong>No notifications</strong><span>{loading?"Loading your inbox…":"You are all caught up."}</span></div>}</aside>}
  <main className="workspace-main"><div className="preview-banner"><span>{live?"AUTHENTICATED WORKSPACE":"VALIDATION WORKSPACE"}</span>{live?"Live tenant-scoped documents, reviews, and notifications":"Demonstration records only — sign in to load live records"}</div><div className="page-heading"><div><p className="eyebrow">POLICY &amp; DOCUMENTATION</p><h1>{view}</h1><p>{view==="Documents"?"Manage controlled content, approvals, effective versions, and review schedules.":view==="Review queue"?"Monitor current-version periodic reviews and overdue work.":"Monitor notification delivery failures and controlled recovery."}</p></div>{view==="Documents"&&<button className="primary-button" disabled={live!==null&&!live.capabilities.canCreateDocuments} onClick={()=>setDialog(true)}><Icon name="plus"/>New document</button>}</div>{notice&&<div className="notice" role="status"><Icon name="check"/><span>{notice}</span><button aria-label="Dismiss notification" onClick={()=>setNotice("")}><Icon name="close"/></button></div>}
  <section className="metric-grid" aria-label="Workspace summary"><article><span className="metric-icon blue"><Icon name="file"/></span><div><span>{live?"PAGE RESULTS":"CONTROLLED DOCUMENTS"}</span><strong>{live?documents.length:128}</strong><small>{live?"Tenant-scoped query":"Validation dataset"}</small></div></article><article><span className="metric-icon amber"><Icon name="review"/></span><div><span>OPEN REVIEWS</span><strong>{live?.reviews.length??4}</strong><small>{overdue} overdue</small></div></article><article><span className="metric-icon violet"><Icon name="bell"/></span><div><span>UNREAD NOTIFICATIONS</span><strong>{unread}</strong><small>Recipient-owned inbox</small></div></article><article><span className="metric-icon green"><Icon name="check"/></span><div><span>DELIVERY FAILURES</span><strong>{live?.failures.length??0}</strong><small>Administrator visibility</small></div></article></section>
  {view==="Documents"&&<section className="panel documents-panel"><div className="panel-header"><div><h2>Controlled documents</h2><p>{live?"Tenant-scoped current and in-process versions":"Demonstration current and in-process versions"}</p></div></div><div className="toolbar"><div className="table-search"><Icon name="search"/><input value={query} onChange={e=>resetDocumentQuery(e.target.value,undefined)} placeholder="Search title, number, or type" aria-label="Search documents"/></div><select value={filter} onChange={e=>resetDocumentQuery(undefined,e.target.value)} aria-label="Filter by status"><option value="ALL">All documents</option><option value="EFFECTIVE">Effective</option><option value="IN_REVIEW">In review</option><option value="APPROVED">Approved</option><option value="DRAFT">Draft</option><option value="SUPERSEDED">Superseded</option><option value="RETIRED">Retired</option></select></div>{documentsError&&<div className="permission-state"><Icon name="shield"/><strong>Documents unavailable</strong><span>{documentsError}</span></div>}{live&&!live.capabilities.canReadDocuments?<div className="permission-state"><Icon name="shield"/><strong>Document access required</strong><span>Your account cannot view controlled document versions.</span></div>:<><div className="table-wrap"><table><thead><tr><th>Document</th><th>Status</th><th>Version</th><th>Owner</th><th>Effective</th><th>Review due</th></tr></thead><tbody>{visible.map(document=><tr key={`${document.id}-${document.version}`}><td><a href="#">{document.title}</a><span>{document.id} · {document.type}</span></td><td><StatusBadge status={document.status}/></td><td>v{document.version}</td><td>{document.owner}</td><td>{document.effective}</td><td className={document.status==="Review due"?"due":""}>{document.due}</td></tr>)}</tbody></table>{!documentsLoading&&!visible.length&&<div className="empty-state"><Icon name="file"/><strong>No documents found</strong><span>Adjust the search or status filter.</span></div>}</div>{live&&<div className="table-footer"><span>{documentsLoading?"Loading controlled documents…":`${documents.length} result${documents.length===1?"":"s"} on this page`}</span><div><button disabled={!cursor||documentsLoading} onClick={()=>{const history=[...cursorHistory];setCursor(history.pop()??null);setCursorHistory(history);}}>Previous</button><button disabled={!nextCursor||documentsLoading} onClick={()=>{setCursorHistory(history=>[...history,cursor]);setCursor(nextCursor);}}>Next</button></div></div>}</>}</section>}
  {view==="Review queue"&&<section className="panel documents-panel"><div className="panel-header"><div><h2>Periodic review queue</h2><p>Only current effective versions are shown</p></div><span className="count-pill">{live?.reviews.length??0}</span></div>{live?.capabilities.canManageReviews?<div className="table-wrap"><table><thead><tr><th>Document</th><th>Version</th><th>Review due</th><th>Status</th></tr></thead><tbody>{live.reviews.map(review=><tr key={review.id}><td><a href="#">{review.title}</a><span>{review.documentNumber}</span></td><td>v{review.revisionLabel}</td><td className={review.overdue?"due":""}>{date(review.dueAt)}</td><td><span className={`status ${review.overdue?"status-review-due":"status-effective"}`}><span/>{review.overdue?"Overdue":"Scheduled"}</span></td></tr>)}</tbody></table>{!live.reviews.length&&<div className="empty-state"><Icon name="check"/><strong>No outstanding reviews</strong><span>All current effective versions are within schedule.</span></div>}</div>:<div className="permission-state"><Icon name="shield"/><strong>Review management access required</strong><span>Your account cannot view the organization-wide periodic review queue.</span></div>}</section>}
  {view==="Administration"&&<section className="panel documents-panel"><div className="panel-header"><div><h2>Notification delivery monitoring</h2><p>Failed and dead-letter deliveries only</p></div><span className="count-pill">{live?.failures.length??0}</span></div>{live?.capabilities.canManageNotifications?<div className="table-wrap"><table><thead><tr><th>Status</th><th>Attempts</th><th>Next attempt</th><th>Last error</th><th>Recovery</th></tr></thead><tbody>{live.failures.map(item=><tr key={item.id}><td><span className="status status-review-due"><span/>{item.status.replace("_"," ")}</span></td><td>{item.attempts}</td><td>{date(item.availableAt)}</td><td className="error-cell">{item.lastError??"—"}</td><td><button className="text-button" disabled={item.status!=="DEAD_LETTER"} onClick={()=>requeue(item)}>Requeue</button></td></tr>)}</tbody></table>{!live.failures.length&&<div className="empty-state"><Icon name="check"/><strong>Delivery queue healthy</strong><span>No failed or dead-letter notifications.</span></div>}</div>:<div className="permission-state"><Icon name="shield"/><strong>Administrator access required</strong><span>Your account cannot view delivery diagnostics.</span></div>}</section>}
  </main></div>
  {dialog&&<div className="modal-backdrop" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&setDialog(false)}><div className="modal" role="dialog" aria-modal="true" aria-labelledby="new-title"><div className="modal-head"><div><span className="modal-icon"><Icon name="file"/></span><div><h2 id="new-title">Create controlled document</h2><p>Start a new document at draft version 0.1.</p></div></div><button aria-label="Close dialog" onClick={()=>setDialog(false)}><Icon name="close"/></button></div>{live?.capabilities.canCreateDocuments?<form onSubmit={createDraft}><label>Document title<input name="title" required maxLength={500} autoFocus/></label><div className="form-row"><label>Document number<input name="number" required maxLength={100} placeholder="SOP-000"/></label><label>Document type<select name="type" required>{documentTypes.map(type=><option value={type.id} key={type.id}>{type.code} · {type.name}</option>)}</select></label></div><label>Initial document content<textarea name="content" required maxLength={1000000}/></label><label>Change summary<textarea name="summary" required maxLength={4000}/></label><div className="form-note"><Icon name="shield"/><span>The server derives the tenant and author from the session, hashes the content, and writes the draft with audit evidence.</span></div><div className="modal-actions"><button type="button" onClick={()=>setDialog(false)}>Cancel</button><button className="primary-button" type="submit" disabled={submitting||!documentTypes.length}>{submitting?"Creating…":"Create draft"}</button></div></form>:<div className="permission-state"><Icon name="shield"/><strong>Authenticated creation access required</strong><span>Sign in with document creation permission to start a controlled draft.</span></div>}</div></div>}
 </div>;
}
