"use client";
import { useEffect,useMemo,useState,type FormEvent } from "react";
import { Icon,type IconName } from "./icon";
import { filterDashboardDocuments,summarizeOperationalData } from "@/lib/documents/dashboard";

type Status="Effective"|"In review"|"Draft"|"Review due";
type DocumentRow={id:string;title:string;type:string;version:string;status:Status;owner:string;effective:string;due:string};
type ReviewRow={id:string;documentNumber:string;title:string;revisionLabel:string;dueAt:string;overdue:boolean};
type NotificationRow={id:string;templateKey:string;payload:unknown;sentAt:string|null;readAt:string|null};
type FailureRow={id:string;status:string;attempts:number;lastError:string|null;availableAt:string};
type LiveData={organizationId:string;capabilities:{canManageReviews:boolean;canManageNotifications:boolean};notifications:NotificationRow[];reviews:ReviewRow[];failures:FailureRow[]};
type View="Documents"|"Review queue"|"Administration";
const initialDocuments:DocumentRow[]=[
 {id:"SOP-001",title:"Specimen Collection and Handling",type:"Standard Operating Procedure",version:"4.2",status:"Effective",owner:"Quality Systems",effective:"Aug 12, 2026",due:"Aug 12, 2027"},
 {id:"POL-014",title:"Document and Record Control",type:"Quality Policy",version:"3.0",status:"In review",owner:"James Ramsey",effective:"—",due:"Aug 28, 2026"},
 {id:"WI-032",title:"Daily Temperature Monitoring",type:"Work Instruction",version:"2.1",status:"Review due",owner:"Laboratory Operations",effective:"Sep 3, 2025",due:"Sep 3, 2026"},
 {id:"FRM-022",title:"Corrective Action Investigation",type:"Controlled Form",version:"1.0",status:"Draft",owner:"Quality Systems",effective:"—",due:"—"},
];
const nav:{label:string;icon:IconName}[]=[{label:"Documents",icon:"file"},{label:"Review queue",icon:"review"},{label:"Administration",icon:"settings"}];
const date=(value:string|null)=>value?new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric"}).format(new Date(value)):"—";
function StatusBadge({status}:{status:Status}){return <span className={`status status-${status.toLowerCase().replace(" ","-")}`}><span/>{status}</span>}
function payloadSummary(payload:unknown){if(!payload||typeof payload!=="object")return "Quality system notification";const p=payload as Record<string,unknown>;return typeof p.documentId==="string"?`Document ${p.documentId.slice(0,8)} · escalation level ${String(p.level??1)}`:"Quality system notification";}

export function DocumentControlDashboard(){
 const[documents,setDocuments]=useState(initialDocuments),[query,setQuery]=useState(""),[filter,setFilter]=useState("All documents"),[dialog,setDialog]=useState(false),[mobileNav,setMobileNav]=useState(false),[notice,setNotice]=useState(""),[view,setView]=useState<View>("Documents"),[live,setLive]=useState<LiveData|null>(null),[inboxOpen,setInboxOpen]=useState(false),[loading,setLoading]=useState(true);
 const visible=useMemo(()=>filterDashboardDocuments(documents,query,filter),[documents,query,filter]);
 const summary=summarizeOperationalData({notifications:live?.notifications??[],reviews:live?.reviews??[],failures:live?.failures??[]}),unread=summary.unread,overdue=summary.overdue;
 useEffect(()=>{let active=true;fetch("/api/workspace/dashboard",{credentials:"same-origin"}).then(async response=>response.ok?response.json():null).then(body=>{if(active&&body?.data)setLive(body.data)}).catch(()=>{}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
 function createDraft(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget),title=String(form.get("title")),code=String(form.get("number")),type=String(form.get("type"));setDocuments(current=>[{id:code,title,type,version:"0.1",status:"Draft",owner:"James Ramsey",effective:"—",due:"—"},...current]);setDialog(false);setNotice(`${code} was added to this preview as a draft. Server persistence requires an authenticated organization session.`)}
 async function markRead(item:NotificationRow){if(!live||item.readAt)return;const response=await fetch("/api/notifications",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({operation:"READ",organizationId:live.organizationId,notificationId:item.id})});if(response.ok)setLive({...live,notifications:live.notifications.map(row=>row.id===item.id?{...row,readAt:new Date().toISOString()}:row)});}
 async function requeue(item:FailureRow){if(!live)return;const response=await fetch("/api/notifications",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({operation:"REQUEUE",organizationId:live.organizationId,notificationId:item.id})});if(response.ok){setLive({...live,failures:live.failures.filter(row=>row.id!==item.id)});setNotice("Dead-letter notification was requeued and the action was audited.")}}
 return <div className="app-shell">
  <aside className={`sidebar ${mobileNav?"sidebar-open":""}`}><div className="brand"><div className="brand-mark"><Icon name="shield"/></div><div><strong>TRACE</strong><span>QUALITY SYSTEMS</span></div></div><button className="sidebar-close" aria-label="Close navigation" onClick={()=>setMobileNav(false)}><Icon name="close"/></button><div className="workspace"><span>WORKSPACE</span><button>Trace Scientific<Icon name="chevron"/></button></div><nav aria-label="Primary navigation">{nav.map(item=><button key={item.label} className={view===item.label?"active":""} onClick={()=>{setView(item.label as View);setMobileNav(false)}}><Icon name={item.icon}/><span>{item.label}</span>{item.label==="Review queue"&&overdue>0&&<b>{overdue}</b>}</button>)}</nav><div className="sidebar-foot"><div className="compliance"><Icon name="shield"/><div><strong>Audit controls active</strong><span>Evidence is append-only</span></div></div><div className="user-card"><div className="avatar">JR</div><div><strong>James Ramsey</strong><span>Quality Administrator</span></div><Icon name="more"/></div></div></aside>
  <div className="main-column"><header className="topbar"><button className="mobile-menu" aria-label="Open navigation" onClick={()=>setMobileNav(true)}><Icon name="menu"/></button><div className="global-search"><Icon name="search"/><input aria-label="Global search" placeholder="Search QMS records"/><kbd>⌘ K</kbd></div><button className="icon-button" aria-label={`${unread} unread notifications`} aria-expanded={inboxOpen} onClick={()=>setInboxOpen(!inboxOpen)}><Icon name="bell"/>{unread>0&&<span className="notification-count">{unread}</span>}</button><div className="top-avatar">JR</div></header>
  {inboxOpen&&<aside className="notification-drawer" aria-label="Notifications"><div className="drawer-head"><div><h2>Notifications</h2><p>{unread} unread</p></div><button aria-label="Close notifications" onClick={()=>setInboxOpen(false)}><Icon name="close"/></button></div>{live?.notifications.length?live.notifications.map(item=><button key={item.id} className={`notification-item ${item.readAt?"":"unread"}`} onClick={()=>markRead(item)}><span className="activity-dot amber"><Icon name="clock"/></span><span><strong>{item.templateKey.replaceAll("_"," ")}</strong><small>{payloadSummary(item.payload)}</small><time>{date(item.sentAt)}</time></span></button>):<div className="drawer-empty"><Icon name="bell"/><strong>No notifications</strong><span>{loading?"Loading your inbox…":"You are all caught up."}</span></div>}</aside>}
  <main className="workspace-main"><div className="preview-banner"><span>{live?"AUTHENTICATED WORKSPACE":"VALIDATION WORKSPACE"}</span>{live?"Live tenant-scoped review and notification data":"Demonstration records only — sign in to load live records"}</div><div className="page-heading"><div><p className="eyebrow">POLICY &amp; DOCUMENTATION</p><h1>{view}</h1><p>{view==="Documents"?"Manage controlled content, approvals, effective versions, and review schedules.":view==="Review queue"?"Monitor current-version periodic reviews and overdue work.":"Monitor notification delivery failures and controlled recovery."}</p></div>{view==="Documents"&&<button className="primary-button" onClick={()=>setDialog(true)}><Icon name="plus"/>New document</button>}</div>{notice&&<div className="notice" role="status"><Icon name="check"/><span>{notice}</span><button aria-label="Dismiss notification" onClick={()=>setNotice("")}><Icon name="close"/></button></div>}
  <section className="metric-grid" aria-label="Workspace summary"><article><span className="metric-icon blue"><Icon name="file"/></span><div><span>CONTROLLED DOCUMENTS</span><strong>128</strong><small>Validation dataset</small></div></article><article><span className="metric-icon amber"><Icon name="review"/></span><div><span>OPEN REVIEWS</span><strong>{live?.reviews.length??4}</strong><small>{overdue} overdue</small></div></article><article><span className="metric-icon violet"><Icon name="bell"/></span><div><span>UNREAD NOTIFICATIONS</span><strong>{unread}</strong><small>Recipient-owned inbox</small></div></article><article><span className="metric-icon green"><Icon name="check"/></span><div><span>DELIVERY FAILURES</span><strong>{live?.failures.length??0}</strong><small>Administrator visibility</small></div></article></section>
  {view==="Documents"&&<section className="panel documents-panel"><div className="panel-header"><div><h2>Controlled documents</h2><p>Current and in-process versions</p></div></div><div className="toolbar"><div className="table-search"><Icon name="search"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search title, number, or type" aria-label="Search documents"/></div><select value={filter} onChange={e=>setFilter(e.target.value)} aria-label="Filter by status"><option>All documents</option><option>Effective</option><option>In review</option><option>Review due</option><option>Draft</option></select></div><div className="table-wrap"><table><thead><tr><th>Document</th><th>Status</th><th>Version</th><th>Owner</th><th>Effective</th><th>Review due</th></tr></thead><tbody>{visible.map(document=><tr key={`${document.id}-${document.version}`}><td><a href="#">{document.title}</a><span>{document.id} · {document.type}</span></td><td><StatusBadge status={document.status}/></td><td>v{document.version}</td><td>{document.owner}</td><td>{document.effective}</td><td className={document.status==="Review due"?"due":""}>{document.due}</td></tr>)}</tbody></table></div></section>}
  {view==="Review queue"&&<section className="panel documents-panel"><div className="panel-header"><div><h2>Periodic review queue</h2><p>Only current effective versions are shown</p></div><span className="count-pill">{live?.reviews.length??0}</span></div>{live?.capabilities.canManageReviews?<div className="table-wrap"><table><thead><tr><th>Document</th><th>Version</th><th>Review due</th><th>Status</th></tr></thead><tbody>{live.reviews.map(review=><tr key={review.id}><td><a href="#">{review.title}</a><span>{review.documentNumber}</span></td><td>v{review.revisionLabel}</td><td className={review.overdue?"due":""}>{date(review.dueAt)}</td><td><span className={`status ${review.overdue?"status-review-due":"status-effective"}`}><span/>{review.overdue?"Overdue":"Scheduled"}</span></td></tr>)}</tbody></table>{!live.reviews.length&&<div className="empty-state"><Icon name="check"/><strong>No outstanding reviews</strong><span>All current effective versions are within schedule.</span></div>}</div>:<div className="permission-state"><Icon name="shield"/><strong>Review management access required</strong><span>Your account cannot view the organization-wide periodic review queue.</span></div>}</section>}
  {view==="Administration"&&<section className="panel documents-panel"><div className="panel-header"><div><h2>Notification delivery monitoring</h2><p>Failed and dead-letter deliveries only</p></div><span className="count-pill">{live?.failures.length??0}</span></div>{live?.capabilities.canManageNotifications?<div className="table-wrap"><table><thead><tr><th>Status</th><th>Attempts</th><th>Next attempt</th><th>Last error</th><th>Recovery</th></tr></thead><tbody>{live.failures.map(item=><tr key={item.id}><td><span className="status status-review-due"><span/>{item.status.replace("_"," ")}</span></td><td>{item.attempts}</td><td>{date(item.availableAt)}</td><td className="error-cell">{item.lastError??"—"}</td><td><button className="text-button" disabled={item.status!=="DEAD_LETTER"} onClick={()=>requeue(item)}>Requeue</button></td></tr>)}</tbody></table>{!live.failures.length&&<div className="empty-state"><Icon name="check"/><strong>Delivery queue healthy</strong><span>No failed or dead-letter notifications.</span></div>}</div>:<div className="permission-state"><Icon name="shield"/><strong>Administrator access required</strong><span>Your account cannot view delivery diagnostics.</span></div>}</section>}
  </main></div>
  {dialog&&<div className="modal-backdrop" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&setDialog(false)}><div className="modal" role="dialog" aria-modal="true" aria-labelledby="new-title"><div className="modal-head"><div><span className="modal-icon"><Icon name="file"/></span><div><h2 id="new-title">Create controlled document</h2><p>Start a new document at draft version 0.1.</p></div></div><button aria-label="Close dialog" onClick={()=>setDialog(false)}><Icon name="close"/></button></div><form onSubmit={createDraft}><label>Document title<input name="title" required maxLength={500} autoFocus/></label><div className="form-row"><label>Document number<input name="number" required maxLength={100} placeholder="SOP-000"/></label><label>Document type<select name="type" required><option>Standard Operating Procedure</option><option>Quality Policy</option><option>Work Instruction</option><option>Controlled Form</option></select></label></div><label>Change summary<textarea name="summary" required maxLength={4000}/></label><div className="form-note"><Icon name="shield"/><span>The server verifies organization, permissions, revision metadata, and content hash before saving.</span></div><div className="modal-actions"><button type="button" onClick={()=>setDialog(false)}>Cancel</button><button className="primary-button" type="submit">Create draft</button></div></form></div></div>}
 </div>;
}
