import { Prisma } from "@prisma/client";
import { db } from "../db";
import { QualityClosureValidationError, type QualityClosureEvidence, type QualityClosureRecord, type QualityClosureStore } from "./closure";

export class PrismaQualityClosureStore implements QualityClosureStore{
  recentFailedReauthentications(organizationId:string,userId:string,since:Date){return db.authenticationEvent.count({where:{organizationId,userId,eventType:"REAUTHENTICATION",outcome:"FAILURE",occurredAt:{gte:since},metadata:{path:["purpose"],equals:"QUALITY_EVENT_CLOSURE"}}});}
  async loadEvidence(organizationId:string,userId:string,eventId:string):Promise<QualityClosureEvidence|null>{
    const user=await db.user.findFirst({where:{organizationId,id:userId,status:"ACTIVE",credential:{disabledAt:null}},select:{credential:{select:{passwordHash:true}}}});if(!user?.credential)return null;
    const rows=await db.$queryRaw<Array<{id:string;eventNumber:string;status:string}>>(Prisma.sql`SELECT "id","eventNumber","status"::text AS "status" FROM "QualityEvent" WHERE "organizationId"=${organizationId}::uuid AND "id"=${eventId}::uuid`);const event=rows[0];if(!event)return null;
    return {organizationId,userId,passwordHash:user.credential.passwordHash,eventId:event.id,eventNumber:event.eventNumber,status:event.status};
  }
  async loadClosure(organizationId:string,eventId:string):Promise<QualityClosureRecord|null>{
    const rows=await db.$queryRaw<QualityClosureRecord[]>(Prisma.sql`SELECT c."id" AS "closureId",c."eventId",q."eventNumber",c."closureReason",c."closedAt",c."closedByUserId" AS "signerUserId",TRIM(CONCAT(u."firstName",' ',u."lastName")) AS "signerName",u."email" AS "signerEmail",s."id" AS "signatureId",s."meaning"::text AS "meaning",s."meaningText",s."signedAt",s."authenticationEventId",a."method"::text AS "authenticationMethod",a."outcome"::text AS "authenticationOutcome",s."payloadHash" FROM "QualityEventClosure" c JOIN "QualityEvent" q ON q."organizationId"=c."organizationId" AND q."id"=c."eventId" JOIN "ElectronicSignature" s ON s."organizationId"=c."organizationId" AND s."id"=c."signatureId" JOIN "AuthenticationEvent" a ON a."organizationId"=c."organizationId" AND a."id"=s."authenticationEventId" JOIN "User" u ON u."organizationId"=c."organizationId" AND u."id"=c."closedByUserId" WHERE c."organizationId"=${organizationId}::uuid AND c."eventId"=${eventId}::uuid LIMIT 1`);
    return rows[0]??null;
  }
  async recordFailedReauthentication(evidence:QualityClosureEvidence,occurredAt:Date){await db.$transaction([db.authenticationEvent.create({data:{organizationId:evidence.organizationId,userId:evidence.userId,eventType:"REAUTHENTICATION",outcome:"FAILURE",method:"PASSWORD",occurredAt,metadata:{purpose:"QUALITY_EVENT_CLOSURE"}}}),db.auditEvent.create({data:{organizationId:evidence.organizationId,actorUserId:evidence.userId,action:"QUALITY_EVENT_CLOSURE_REAUTHENTICATION_FAILED",entityType:"QualityEvent",entityId:evidence.eventId,occurredAt,metadata:{eventNumber:evidence.eventNumber}}})]);}
  async commitClosure(input:Parameters<QualityClosureStore["commitClosure"]>[0]){
    return db.$transaction(async tx=>{
      const events=await tx.$queryRaw<Array<{status:string}>>(Prisma.sql`SELECT "status"::text AS "status" FROM "QualityEvent" WHERE "organizationId"=${input.organizationId}::uuid AND "id"=${input.eventId}::uuid FOR UPDATE`);const event=events[0];if(!event)throw new QualityClosureValidationError("Quality event not found");if(event.status!=="VERIFICATION")throw new QualityClosureValidationError("Quality event must be in VERIFICATION before closure");
      const investigations=await tx.$queryRaw<Array<{count:bigint}>>(Prisma.sql`SELECT COUNT(*)::bigint AS "count" FROM "QualityEventInvestigation" WHERE "organizationId"=${input.organizationId}::uuid AND "eventId"=${input.eventId}::uuid`);if(Number(investigations[0]?.count??0)<1)throw new QualityClosureValidationError("Investigation evidence is required before closure");
      const capa=await tx.$queryRaw<Array<{total:bigint;open:bigint;withoutPass:bigint}>>(Prisma.sql`SELECT COUNT(*)::bigint AS "total",COUNT(*) FILTER (WHERE a."status"='OPEN')::bigint AS "open",COUNT(*) FILTER (WHERE a."status"='COMPLETED' AND NOT EXISTS (SELECT 1 FROM "QualityEffectivenessCheck" e WHERE e."organizationId"=a."organizationId" AND e."eventId"=a."eventId" AND e."capaActionId"=a."id" AND e."result"='PASS'))::bigint AS "withoutPass" FROM "QualityCapaAction" a WHERE a."organizationId"=${input.organizationId}::uuid AND a."eventId"=${input.eventId}::uuid`);const gates=capa[0];if(Number(gates?.total??0)<1)throw new QualityClosureValidationError("At least one CAPA action is required before closure");if(Number(gates?.open??0)>0)throw new QualityClosureValidationError("All CAPA actions must be completed before closure");if(Number(gates?.withoutPass??0)>0)throw new QualityClosureValidationError("Every CAPA action requires a passing effectiveness check before closure");
      const prior=await tx.$queryRaw<Array<{id:string}>>(Prisma.sql`SELECT "id" FROM "QualityEventClosure" WHERE "organizationId"=${input.organizationId}::uuid AND "eventId"=${input.eventId}::uuid`);if(prior[0])throw new QualityClosureValidationError("Quality event is already closed");
      const authentication=await tx.authenticationEvent.create({data:{organizationId:input.organizationId,userId:input.signerUserId,eventType:"REAUTHENTICATION",outcome:"SUCCESS",method:"PASSWORD",occurredAt:input.signedAt,validUntil:input.authenticationValidUntil,metadata:{purpose:"QUALITY_EVENT_CLOSURE"}}});
      const signature=await tx.electronicSignature.create({data:{organizationId:input.organizationId,signerUserId:input.signerUserId,entityType:"QualityEvent",entityId:input.eventId,entityVersion:input.eventNumber,meaning:"COMPLETED",meaningText:"I confirm this quality event is complete, required CAPA actions have been implemented and verified effective, and the event may be closed.",authenticationEventId:authentication.id,payloadHash:input.payloadHash,signedAt:input.signedAt}});
      const closureRows=await tx.$queryRaw<Array<{id:string}>>(Prisma.sql`INSERT INTO "QualityEventClosure" ("organizationId","eventId","closedByUserId","closureReason","signatureId","closedAt") VALUES (${input.organizationId}::uuid,${input.eventId}::uuid,${input.signerUserId}::uuid,${input.closureReason},${signature.id}::uuid,${input.signedAt}) RETURNING "id"`);const closure=closureRows[0];if(!closure)throw new QualityClosureValidationError("Closure evidence could not be recorded");
      await tx.$executeRaw(Prisma.sql`UPDATE "QualityEvent" SET "status"='CLOSED' WHERE "organizationId"=${input.organizationId}::uuid AND "id"=${input.eventId}::uuid`);
      await tx.$executeRaw(Prisma.sql`INSERT INTO "QualityEventChange" ("organizationId","eventId","kind","fromValue","toValue","reason","actorUserId","createdAt") VALUES (${input.organizationId}::uuid,${input.eventId}::uuid,'STATUS','VERIFICATION','CLOSED',${input.closureReason},${input.signerUserId}::uuid,${input.signedAt})`);
      await tx.auditEvent.create({data:{organizationId:input.organizationId,actorUserId:input.signerUserId,action:"QUALITY_EVENT_CLOSED_WITH_SIGNATURE",entityType:"QualityEvent",entityId:input.eventId,occurredAt:input.signedAt,metadata:{eventNumber:input.eventNumber,closureId:closure.id,signatureId:signature.id,authenticationEventId:authentication.id,payloadHash:input.payloadHash}}});
      return {closureId:closure.id,signatureId:signature.id};
    });
  }
}
