export const REVIEWED_HELP_BASELINE = [
  { categoryCode:"GETTING_STARTED", categoryName:"Getting started", slug:"controlled-documents", title:"Controlled documents", summary:"Create, revise, submit, review, approve, distribute, and acknowledge controlled documents.", body:"Use Documents for governed document lifecycle work. Create or revise only when your assigned permissions allow it. Submit completed drafts into review, complete assigned reviews, and approve only within your authorized scope. Effective, superseded, retired, distributed, and acknowledged states remain controlled system records. Do not bypass required signatures, review assignments, or effective-date controls.", changeSummary:"Initial reviewed launch guidance." },
  { categoryCode:"WORKFLOWS", categoryName:"QMS workflows", slug:"review-queue-approvals", title:"Review queues and approvals", summary:"Work assigned reviews and approvals without bypassing controlled workflow.", body:"Use Review queue to see periodic reviews, overdue work, and approval assignments available to your account. Open the governed item, verify the current revision and supporting evidence, then complete only the action assigned to you. Rejection or return-for-revision decisions should include a clear reason. Do not approve on behalf of another user or share credentials.", changeSummary:"Initial reviewed launch guidance." },
  { categoryCode:"WORKFLOWS", categoryName:"QMS workflows", slug:"records-management", title:"Records management", summary:"Create, retain, archive, and export governed records.", body:"Use Records for governed quality records and their configured record types. Create records with accurate metadata and permitted evidence. Archived records remain historical evidence and are not ordinary editable content. Export only through authorized record-export functions and preserve retention or legal-hold controls.", changeSummary:"Initial reviewed launch guidance." },
  { categoryCode:"WORKFLOWS", categoryName:"QMS workflows", slug:"personnel-credentials-qualifications", title:"Personnel, credentials, and qualifications", summary:"Maintain governed personnel evidence and qualification status.", body:"Use Personnel to manage people, assignments, credentials, and qualifications according to your permissions. Attach only approved evidence types. Expiration and qualification status affect operational readiness; do not alter historical evidence to extend validity. Create new governed evidence when status changes.", changeSummary:"Initial reviewed launch guidance." },
  { categoryCode:"WORKFLOWS", categoryName:"QMS workflows", slug:"training-competency", title:"Training and competency", summary:"Manage training assignments, completions, competency programs, and assessments.", body:"Use Training & competency to assign governed training, record completion evidence, and assess competency. Completion and assessment records must reflect the actual performer, date, outcome, and evidence. Expired or failed competency should be handled through the configured lifecycle rather than by changing historical records.", changeSummary:"Initial reviewed launch guidance." },
  { categoryCode:"WORKFLOWS", categoryName:"QMS workflows", slug:"quality-events", title:"Quality events", summary:"Create, investigate, CAPA, review, and close quality events.", body:"Use Quality events to document deviations, nonconformances, complaints, CAPA, and related events supported by your configuration. Record facts, impact, investigation, actions, and closure evidence. Preserve the original event history; corrections and follow-up should be attributable and auditable.", changeSummary:"Initial reviewed launch guidance." },
  { categoryCode:"LAB_OPERATIONS", categoryName:"Laboratory operations", slug:"equipment-operations", title:"Equipment operations", summary:"Qualification, calibration, maintenance, service, holds, and return to service.", body:"Use Laboratory operations for governed equipment activities. Record qualification, calibration, maintenance, service, out-of-service, impact assessment, and return-to-service evidence as applicable. Do not use equipment whose status or required evidence makes it unavailable for intended work.", changeSummary:"Initial reviewed launch guidance." },
  { categoryCode:"REPORTING", categoryName:"Reporting & analytics", slug:"governed-reporting", title:"Governed reporting and exports", summary:"Run and export governed reports without bypassing source-record controls.", body:"Use Reporting & analytics to review authorized operational and quality information. Report output does not replace the underlying governed record. Export only through authorized functions, verify filters and date ranges, and retain output according to applicable policy when it becomes controlled evidence.", changeSummary:"Initial reviewed launch guidance." },
  { categoryCode:"ADMIN", categoryName:"Administration", slug:"tenant-administration", title:"Tenant administration and configuration", summary:"Manage access, document configuration, workflows, notifications, and audit settings.", body:"Use Administration only when assigned administrative permission. Apply least privilege, keep roles and memberships attributable, and use governed configuration controls for document types, workflows, notifications, and retention. Administrative access does not bypass document approval, signatures, training, quality, or audit requirements.", changeSummary:"Initial reviewed launch guidance." }
] as const;
